version: 2.1
jobs:
  build:
    working_directory: ~/app
    
    machine:
     services:
       - docker

    dependencies:
      pre:
        - pip install docker-compose

    test:
      pre:
        - docker-compose up -d
    
    steps:
      - checkout
      - run:
          name: compose
          command: docker-compose run app sh -c "python manage.py test"