version: 2.1

jobs:
  build:
    
    docker:
      - image: cimg/python:3.10.0
    
    pre-steps:
      - run:
          command: pip install docker-compose

    steps:
      - checkout
      - run: python --version